apiVersion: v1
kind: Namespace
metadata:
  name: home-cloud-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-home-cloud-apps
  namespace: home-cloud-system
rules:
- apiGroups: ["home-cloud.io"]
  resources: ["apps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-home-cloud-apps
  namespace: home-cloud-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: home-cloud-system
roleRef:
  kind: Role
  name: manage-home-cloud-apps
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-cloud-server-read-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pods
subjects:
- kind: ServiceAccount
  name: default
  namespace: home-cloud-system
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: home-cloud-system
spec:
  ports:
  - name: http
    port: 8090
  selector:
    app: server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server
  namespace: home-cloud-system
data:
  config.yaml: |
    service:
      name: server
      domain: home-cloud
      env: prod
      entrypoint: http://blueprint.draft-system.svc.cluster.local:8090
      network:
        internal:
          host: server.home-cloud-system.svc.cluster.local
          port: 8090
        external:
          host: home-cloud.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: home-cloud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/home-cloud-io/core-platform-server:v0.0.19
          ports:
          - containerPort: 8090
          volumeMounts:
          - name: config
            mountPath: /etc/config.yaml
            subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: server
