apiVersion: v1
kind: Namespace
metadata:
  name: home-cloud-server
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: home-cloud-server
spec:
  ports:
  - name: http
    port: 8090
  selector:
    app: server
---
# TODO: replace this with Fuse
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: server
  namespace: home-cloud-server
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`home-cloud.local`)"
      kind: Rule
      services:
        - name: server
          port: 8090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server
  namespace: home-cloud-server
data:
  config.yaml: |
    service:
      name: home-cloud-server
      env: prod
      logging:
        level: info
      port: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: home-cloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/home-cloud-io/server:v0.0.2
          imagePullPolicy: 'IfNotPresent'
          volumeMounts:
          - name: config
            mountPath: /etc/config.yaml
            subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: server
